//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCEJobs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Dynalectric\\z\\Files\\")]
        public string FormsLocation {
            get {
                return ((string)(this["FormsLocation"]));
            }
            set {
                this["FormsLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q/sKm2JGfXp5g4YFH2bltg==")]
        public string u1 {
            get {
                return ((string)(this["u1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pMbkfVS8OJcjxzmQJ+jJFQ==")]
        public string u2 {
            get {
                return ((string)(this["u2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynalectric Company ")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Dynalectric\\z\\ProjectOpportunity\\")]
        public string ProjectOpportunityLocation {
            get {
                return ((string)(this["ProjectOpportunityLocation"]));
            }
            set {
                this["ProjectOpportunityLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\SG3-Logs\\")]
        public string LogFile {
            get {
                return ((string)(this["LogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC2\\SQLEXPRESS")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JCCProd")]
        public string database {
            get {
                return ((string)(this["database"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Estimates\\")]
        public string EstimatesLocation {
            get {
                return ((string)(this["EstimatesLocation"]));
            }
            set {
                this["EstimatesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jobs\\")]
        public string JobsLocation {
            get {
                return ((string)(this["JobsLocation"]));
            }
            set {
                this["JobsLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProfilePicLocation\\")]
        public string ProfilePicLocation
        {
            get
            {
                return ((string)(this["ProfilePicLocation"]));
            }
            set
            {
                this["ProfilePicLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DestinationPicLocation\\")]
        public string DestinationPicLocation
        {
            get
            {
                return ((string)(this["DestinationPicLocation"]));
            }
            set
            {
                this["DestinationPicLocation"] = value;
            }
        }



        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Dynalectric\\z\\Templates\\")]
        public string ExcelTemplatesLocation {
            get {
                return ((string)(this["ExcelTemplatesLocation"]));
            }
            set {
                this["ExcelTemplatesLocation"] = value;
            }
        }
    }
}
